### ISSUE TITLE
avoid auto start eglot?

### ISSUE THREAD

**Issue by uliw** [emacs-grammarly/eglot-grammarly#12]
Currently, I have
```lisp
:hook ((text-mode markdown-mode). (lambda ()
				      (require 'eglot-grammarly)
				      (eglot-ensure)))
```
However, `eglot-ensure` will start the server whenever I enter a markdown buffer. However, that is only sometimes desirable.  Is there a way to associate eglot-grammarly with a given mode without starting it right away?

**Comment by jcs090218** [comment]
You would have to call it manually `M-x eglot`.

**Comment by uliw** [comment]
yep, but then I get:
```
[eglot] Couldn't guess LSP server for `org-mode'
Enter program to execute (or <host>:<port>): 
```
So how to make the connection between the mode and the server without starting it right away?

**Comment by jcs090218** [comment]
You would need this only then:

```elisp
(require 'eglot-grammarly)
```

**Comment by uliw** [comment]
splendid, the following works as hoped. Thx!

```lisp
(use-package eglot-grammarly
  :straight (:host github :repo "emacs-grammarly/eglot-grammarly")
  :defer t  ; defer package loading
  :hook ((text-mode markdown-mode). (lambda ()
				      (require 'eglot-grammarly)))
  :hook ((text-mode org-mode). (lambda ()
 				 (require 'eglot-grammarly)))
  )
```
