### ISSUE TITLE
Does it work without initializing the clientId?

### ISSUE THREAD

**Issue by sychen52** [emacs-grammarly/eglot-grammarly#3]
Does the current version work for you guys? For me, it complaints that the clientId is not initialized.
I checked the implementation in lsp-grammarly. And there they also have an initialization step.
I was able to get it to work with the following code. It is modified based on the example in eglot readme and lsp-grammarly. I can submit a pull request if you want.

```
(add-to-list 'eglot-server-programs '((text-mode markdown-mode)
                                      .
                                      (eglot-grammarly
                                       "grammarly-languageserver"
                                       "--stdio")))
(defclass eglot-grammarly (eglot-lsp-server) ()
  :documentation "A custom class for grammarly langserver.")
(cl-defmethod eglot-initialization-options ((server eglot-grammarly))
  "Passes through required grammarly initialization options"
    (list :clientId "client_BaDkMgx4X19X9UxxYRCXZo"))
```

**Comment by jcs090218** [comment]
Ah... you are right, I somehow overlooked this part while implementing this. It would **NOT** work without specifying the `clientId`.

Open a PR would be great! :D
