### ISSUE TITLE
This package is not on melpa, so the use-package example in readme does not work.

### ISSUE THREAD

**Issue by sychen52** [emacs-grammarly/eglot-grammarly#5]
I guess this may turn some of the potential users away.
I have an example using straight.el and use-package as below. If you want, I can do a pull request to update the README.
```
 (use-package eglot-grammarly
  :straight (:host github :repo "emacs-grammarly/eglot-grammarly")
  :defer t
  :hook ((text-mode markdown-mode). (lambda ()
                                      (require 'eglot-grammarly)
                                      (call-interactively #'eglot))))
```

**Comment by jcs090218** [comment]
The plan was to add this to melpa, but it never happened. I have added to my own elpa ([jcs-elpa](https://github.com/jcs-emacs/jcs-elpa)) just in case if anyone want to use it with `package.el`.

PRs are always welcome! :)
